version: "3"
services:
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=password
    container_name: eshop_postgres
  mongodb:
    image: mongo:4.0.20
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb/data:/var/lib/mongodb/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: eshop_mongodb
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq/data
    container_name: eshop_rabbitmq
  backend:
    depends_on:
      - cartservice
      - rabbitmq
    image: <<개인 backend Image Registry URI>>:<<개인 backend Image Tag>>
    ports:
      - "8090:8090"
    environment:
      - URL_PRODUCTSERVICE=http://eshopproductservice:8092
      - URL_CARTSERVICE=http://eshopcartservice:8091
      - SPRING_RABBITMQ_HOST=rabbitmq
    container_name: eshopbackend
  frontend:
    depends_on:
      - backend
    image: <<개인 frontend Image Registry URI>>:<<개인 frontend Image Tag>>
    ports:
      - "8080:8080"
    container_name: eshopfrontend
    #command: http-server dist --proxy http://backend:8090
  cartservice:
    depends_on:
      - redis
      - rabbitmq
    image: <<개인 cartservice Image Registry URI>>:<<개인 cartservice Image Tag>>
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8091:8091"
    container_name: eshopcartservice
  productservice:
    depends_on:
      - mongodb
    image: <<개인 productservice Image Registry URI>>:<<개인 productservice Image Tag>>
    environment:
      - PORT=8092
      - MONGO_URI=mongodb://admin:password@mongodb
      - INIT_DATA=true
    ports:
      - "8092:8092"
    container_name: eshopproductservice
  recommendservice:
    depends_on:
      - productservice
    image: <<개인 recommendservice Image Registry URI>>:<<개인 recommendservice Image Tag>>
    environment:
      - URL_PRODUCTSERVICE=http://eshopproductservice:8092
    ports:
      - "8093:8093"
    container_name: eshoprecommendservice
  currencyservice:
    image: <<개인 currencyservice Image Registry URI>>:<<개인 currencyservice Image Tag>>
    ports:
      - "8094:8094"
    container_name: eshopcurrencyservice
  adservice:
    depends_on:
      - postgres
    image: <<개인 adservice Image Registry URI>>:<<개인 adservice Image Tag>>
    ports:
      - "8095:8095"
    container_name: eshopadservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eshop_postgres:5432/eshop_db
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: eshop_nginx_ingress
    depends_on:
      - frontend
      - backend
      - cartservice
      - productservice
      - recommendservice
      - currencyservice
      - adservice
