variable "mariadb_version"          {}
variable "mariadb_storage"          {}
variable "mariadb_port"             {}
variable "mariadb_name"             {}
variable "mariadb_instance_class"   {}
variable "mariadb_master_user_name" {}
variable "vpc_id"                   {}
variable "subnet_id1"               {}
variable "subnet_id2"               {}
